### ISSUE TITLE
could this can be used in Ubuntu18 melodic?

### ISSUE THREAD

**Issue by binbin2002** [hanruihua/rda_ros#2]
Thanks for your good work.
I have a question: could this can bu used in melodic?

**Comment by hanruihua** [comment]
Hi, thank you for your attention.

Theoretically, it could be, but we haven't tested that in Melodic. Some modifications to the command may be needed. We recommend using Noetic, as Melodic is quite old.

**Comment by binbin2002** [comment]
谢谢，您的邮件已经收到，我会尽快进行处理。Thanks! Your e-mail is received and will be handled as soon as possible.
